// Each entry: name, country, dates, x (-10 left … 10 right), y (-10 authoritarian … 10 libertarian),
// blurb (short justification), aliases (lowercase strings people might type)
const POLITICIANS = [
  // --- authoritarian historical/modern rulers ---
  {name:"Omar al-Bashir", country:"Sudan", dates:"1989–2019", x:3, y:-6.5, blurb:"Islamist military ruler, ousted after mass protests.", aliases:["bashir","omar al-bashir","omar bashir"]},
  {name:"Kim Jong-il", country:"North Korea", dates:"1994–2011", x:-9, y:-9.5, blurb:"Totalitarian command economy, absolute personality cult.", aliases:["kim jong il","kim jong-il"]},
  {name:"Kim Jong-un", country:"North Korea", dates:"2011–present", x:-9, y:-9.5, blurb:"Continues totalitarian one-party rule and command economy.", aliases:["kim jong un","kim jong-un","kim"]},
  {name:"Than Shwe", country:"Myanmar/Burma", dates:"1992–2011", x:4, y:-7.5, blurb:"Military junta leader, nationalist economic control.", aliases:["than shwe"]},
  {name:"Robert Mugabe", country:"Zimbabwe", dates:"1980–2017", x:-6, y:-5.8, blurb:"Land redistribution and socialist rhetoric, long one-party rule.", aliases:["mugabe","robert mugabe"]},
  {name:"Islam Karimov", country:"Uzbekistan", dates:"1989–2016", x:-3, y:-7.7, blurb:"Post-Soviet strongman, state-controlled economy.", aliases:["karimov","islam karimov"]},
  {name:"Hu Jintao", country:"China", dates:"2002–2012", x:-5, y:-5.5, blurb:"Socialist market economy under one-party rule.", aliases:["hu jintao"]},
  {name:"Xi Jinping", country:"China", dates:"2012–present", x:-5, y:-7, blurb:"Tightened one-party control, state-directed economy.", aliases:["xi jinping","xi"]},
  {name:"King Abdullah", country:"Saudi Arabia", dates:"2005–2015", x:7, y:-5, blurb:"Absolute monarchy, market economy for elites.", aliases:["king abdullah","abdullah saudi"]},
  {name:"Mohammed bin Salman", country:"Saudi Arabia", dates:"2017–present (Crown Prince/PM)", x:6, y:-5.5, blurb:"Economic liberalization drive alongside tight political control.", aliases:["mbs","mohammed bin salman","bin salman"]},
  {name:"Saparmurat Niyazov", country:"Turkmenistan", dates:"1985–2006", x:-7, y:-9, blurb:"Extreme personality cult, state-controlled economy.", aliases:["niyazov"]},
  {name:"Ali Khamenei", country:"Iran", dates:"1989–present", x:5, y:-6.5, blurb:"Theocratic conservative Supreme Leader.", aliases:["khamenei","ali khamenei"]},
  {name:"Teodoro Obiang Nguema", country:"Equatorial Guinea", dates:"1979–present", x:2, y:-7.5, blurb:"Longest-ruling head of state, oil-fueled kleptocracy.", aliases:["obiang","teodoro obiang"]},
  {name:"Muammar al-Qaddafi", country:"Libya", dates:"1969–2011", x:-7, y:-7, blurb:"\"Islamic socialism,\" anti-capitalist Jamahiriya system.", aliases:["gaddafi","qaddafi","muammar gaddafi"]},
  {name:"King Mswati III", country:"Eswatini/Swaziland", dates:"1986–present", x:6, y:-5.5, blurb:"Absolute monarch, one of the world's last.", aliases:["mswati","king mswati"]},
  {name:"Pervez Musharraf", country:"Pakistan", dates:"1999–2008", x:3, y:-3.5, blurb:"Military ruler with market-friendly reforms.", aliases:["musharraf"]},
  {name:"Aleksandr Lukashenko", country:"Belarus", dates:"1994–present", x:-6.3, y:-6.2, blurb:"Soviet-nostalgic state-controlled economy.", aliases:["lukashenko"]},
  {name:"Fidel Castro", country:"Cuba", dates:"1959–2008", x:-9.5, y:-8, blurb:"Communist one-party state.", aliases:["castro","fidel castro"]},
  {name:"Isaias Afwerki", country:"Eritrea", dates:"1993–present", x:-6, y:-8.3, blurb:"One-party state, no elections ever held.", aliases:["afwerki","isaias"]},
  {name:"Bashar al-Assad", country:"Syria", dates:"2000–2024", x:-4, y:-7.3, blurb:"Ba'athist secular Arab socialism, ousted Dec 2024.", aliases:["assad","bashar al-assad","bashar assad"]},
  {name:"Meles Zenawi", country:"Ethiopia", dates:"1991–2012", x:-5, y:-5, blurb:"Developmental state, \"revolutionary democracy.\"", aliases:["meles zenawi","meles"]},
  {name:"Paul Biya", country:"Cameroon", dates:"1982–present", x:-1, y:-5, blurb:"Personalist rule, nominally socialist party heritage.", aliases:["biya","paul biya"]},
  {name:"Vladimir Putin", country:"Russia", dates:"1999–present", x:1, y:-8, blurb:"State-capitalist economy under centralized authoritarian rule.", aliases:["putin","vladimir putin"]},
  {name:"Nicolás Maduro", country:"Venezuela", dates:"2013–present", x:-8, y:-8, blurb:"Socialist command economy, contested elections.", aliases:["maduro","nicolas maduro"]},
  {name:"Daniel Ortega", country:"Nicaragua", dates:"2007–present", x:-7, y:-8, blurb:"Sandinista socialist rule, crackdowns on opposition.", aliases:["ortega","daniel ortega"]},
  {name:"Recep Tayyip Erdoğan", country:"Turkey", dates:"2003–present", x:2, y:-5.5, blurb:"Conservative-nationalist, growing executive power.", aliases:["erdogan","recep tayyip erdogan"]},

  // --- 20th century dictators/leaders ---
  {name:"Adolf Hitler", country:"Germany", dates:"1933–1945", x:1, y:-10, blurb:"Fascist totalitarian dictatorship.", aliases:["hitler","adolf hitler"]},
  {name:"Joseph Stalin", country:"Soviet Union", dates:"1924–1953", x:-9.5, y:-9.5, blurb:"Totalitarian command economy, mass purges.", aliases:["stalin"]},
  {name:"Mao Zedong", country:"China", dates:"1949–1976", x:-9.5, y:-9, blurb:"Communist revolution, Cultural Revolution repression.", aliases:["mao","mao zedong"]},
  {name:"Benito Mussolini", country:"Italy", dates:"1922–1943", x:2, y:-9, blurb:"Fascist corporatist state.", aliases:["mussolini"]},
  {name:"Francisco Franco", country:"Spain", dates:"1939–1975", x:4, y:-8.5, blurb:"Right-wing nationalist military dictatorship.", aliases:["franco","francisco franco"]},
  {name:"Augusto Pinochet", country:"Chile", dates:"1973–1990", x:6, y:-8, blurb:"Free-market reforms under brutal military rule.", aliases:["pinochet"]},
  {name:"Pol Pot", country:"Cambodia", dates:"1975–1979", x:-9, y:-10, blurb:"Agrarian communist genocide.", aliases:["pol pot"]},
  {name:"Idi Amin", country:"Uganda", dates:"1971–1979", x:-1, y:-9, blurb:"Erratic military dictatorship.", aliases:["idi amin"]},
  {name:"Saddam Hussein", country:"Iraq", dates:"1979–2003", x:-2, y:-9, blurb:"Ba'athist secular nationalist dictatorship.", aliases:["saddam","saddam hussein"]},
  {name:"Slobodan Milošević", country:"Serbia/Yugoslavia", dates:"1989–2000", x:-3, y:-7.5, blurb:"Nationalist authoritarian, ethnic conflict.", aliases:["milosevic"]},
  {name:"Josip Broz Tito", country:"Yugoslavia", dates:"1953–1980", x:-6, y:-4.5, blurb:"Non-aligned market socialism, relatively liberalized communism.", aliases:["tito"]},
  {name:"Nicolae Ceaușescu", country:"Romania", dates:"1965–1989", x:-8, y:-9, blurb:"Hardline Stalinist personality cult.", aliases:["ceausescu"]},
  {name:"Kim Il-sung", country:"North Korea", dates:"1948–1994", x:-9, y:-9.5, blurb:"Founder of totalitarian juche state.", aliases:["kim il sung","kim il-sung"]},
  {name:"Ho Chi Minh", country:"Vietnam", dates:"1945–1969", x:-8, y:-7, blurb:"Communist revolutionary and nation-founder.", aliases:["ho chi minh"]},
  {name:"Deng Xiaoping", country:"China", dates:"1978–1989", x:-3, y:-6.5, blurb:"Market reforms within one-party rule (\"socialism with Chinese characteristics\").", aliases:["deng xiaoping","deng"]},
  {name:"Mikhail Gorbachev", country:"Soviet Union", dates:"1985–1991", x:-6, y:-1, blurb:"Glasnost/perestroika reforms loosened authoritarian control.", aliases:["gorbachev"]},

  // --- widely admired reformers / democratic icons ---
  {name:"Nelson Mandela", country:"South Africa", dates:"1994–1999", x:-4, y:7, blurb:"Anti-apartheid leader, reconciliation-focused democracy.", aliases:["mandela","nelson mandela"]},
  {name:"Mahatma Gandhi", country:"India", dates:"Independence leader", x:-2, y:8, blurb:"Nonviolent independence movement, civil liberties focus.", aliases:["gandhi","mahatma gandhi"]},

  // --- US ---
  {name:"Donald Trump", country:"United States", dates:"2017–2021, 2025–present", x:4, y:-3, blurb:"Right-populist economics, disputed executive-power norms.", aliases:["trump","donald trump","donald j trump"]},
  {name:"Joe Biden", country:"United States", dates:"2021–2025", x:-2, y:4, blurb:"Center-left economics, standard democratic norms.", aliases:["biden","joe biden"]},
  {name:"Barack Obama", country:"United States", dates:"2009–2017", x:-2, y:5, blurb:"Center-left, expanded healthcare access.", aliases:["obama","barack obama"]},
  {name:"George W. Bush", country:"United States", dates:"2001–2009", x:5, y:1, blurb:"Tax cuts, expanded post-9/11 executive/security powers.", aliases:["bush","george w bush","gw bush"]},
  {name:"Bill Clinton", country:"United States", dates:"1993–2001", x:1, y:4, blurb:"Centrist \"Third Way\" economics.", aliases:["clinton","bill clinton"]},
  {name:"Ronald Reagan", country:"United States", dates:"1981–1989", x:7, y:2, blurb:"Free-market deregulation, tax cuts.", aliases:["reagan","ronald reagan"]},
  {name:"Franklin D. Roosevelt", country:"United States", dates:"1933–1945", x:-6, y:2, blurb:"New Deal state intervention in the economy.", aliases:["fdr","franklin roosevelt","franklin d roosevelt"]},
  {name:"Bernie Sanders", country:"United States", dates:"Senator, not head of state", x:-8, y:7, blurb:"Democratic socialist, strong civil-liberties record.", aliases:["bernie","bernie sanders","sanders"]},

  // --- UK ---
  {name:"Keir Starmer", country:"United Kingdom", dates:"2024–present", x:-2, y:4, blurb:"Center-left Labour, standard democratic governance.", aliases:["starmer","keir starmer"]},
  {name:"Rishi Sunak", country:"United Kingdom", dates:"2022–2024", x:5, y:3, blurb:"Fiscally conservative Conservative PM.", aliases:["sunak","rishi sunak"]},
  {name:"Liz Truss", country:"United Kingdom", dates:"2022 (49 days)", x:7, y:3, blurb:"Aggressive free-market tax-cutting agenda.", aliases:["liz truss","truss"]},
  {name:"Boris Johnson", country:"United Kingdom", dates:"2019–2022", x:4, y:1, blurb:"Populist-right, Brexit, some executive overreach controversies.", aliases:["boris johnson","boris"]},
  {name:"Theresa May", country:"United Kingdom", dates:"2016–2019", x:3, y:2, blurb:"Centrist Conservative, Brexit negotiations.", aliases:["theresa may"]},
  {name:"David Cameron", country:"United Kingdom", dates:"2010–2016", x:5, y:3, blurb:"Austerity economics, coalition government.", aliases:["david cameron","cameron"]},
  {name:"Gordon Brown", country:"United Kingdom", dates:"2007–2010", x:-2, y:4, blurb:"Labour, financial-crisis response.", aliases:["gordon brown"]},
  {name:"Tony Blair", country:"United Kingdom", dates:"1997–2007", x:0, y:2, blurb:"\"New Labour\" centrism.", aliases:["tony blair","blair"]},
  {name:"Margaret Thatcher", country:"United Kingdom", dates:"1979–1990", x:8, y:1, blurb:"Privatization, free-market deregulation.", aliases:["thatcher","margaret thatcher"]},
  {name:"Winston Churchill", country:"United Kingdom", dates:"1940–1945, 1951–1955", x:3, y:3, blurb:"Wartime leadership, traditional conservative economics.", aliases:["churchill","winston churchill"]},
  {name:"Andy Burnham", country:"United Kingdom", dates:"2017–present (Gtr Manchester Mayor)", x:-6, y:3, blurb:"Left-leaning Labour, no authoritarian record.", aliases:["andy burnham","burnham"]},
  {name:"Nigel Farage", country:"United Kingdom", dates:"2024–present, Reform UK leader", x:6, y:-2, blurb:"Right-populist, nationalist on immigration.", aliases:["farage","nigel farage"]},
  {name:"Rupert Lowe", country:"United Kingdom", dates:"2025–present, Restore Britain leader", x:8, y:-5, blurb:"Further right and more authoritarian-leaning than Farage.", aliases:["rupert lowe","lowe"]},
  {name:"Jeremy Corbyn", country:"United Kingdom", dates:"Labour leader 2015–2020", x:-8, y:4, blurb:"Democratic socialist, strong civil-liberties positions.", aliases:["corbyn","jeremy corbyn"]},

  // --- France ---
  {name:"Emmanuel Macron", country:"France", dates:"2017–present, President (not PM)", x:3, y:1, blurb:"Centrist market reforms, standard democratic leader.", aliases:["macron","emmanuel macron"]},
  {name:"Marine Le Pen", country:"France", dates:"RN Assembly leader since 2022", x:2, y:-5, blurb:"Nationalist right, protectionist economics.", aliases:["le pen","marine le pen"]},
  {name:"Charles de Gaulle", country:"France", dates:"1959–1969", x:2, y:0, blurb:"Nationalist, strong-executive Fifth Republic founder.", aliases:["de gaulle","charles de gaulle"]},

  // --- Germany ---
  {name:"Friedrich Merz", country:"Germany", dates:"2025–present", x:4, y:2, blurb:"Conservative CDU chancellor, market-oriented.", aliases:["merz","friedrich merz"]},
  {name:"Olaf Scholz", country:"Germany", dates:"2021–2025", x:-1, y:3, blurb:"Center-left SPD chancellor.", aliases:["scholz","olaf scholz"]},
  {name:"Angela Merkel", country:"Germany", dates:"2005–2021", x:1, y:3, blurb:"Centrist CDU, long-tenured stable democratic rule.", aliases:["merkel","angela merkel"]},
  {name:"Helmut Kohl", country:"Germany", dates:"1982–1998", x:3, y:2, blurb:"Center-right, German reunification.", aliases:["kohl","helmut kohl"]},
  {name:"Willy Brandt", country:"Germany", dates:"1969–1974", x:-4, y:4, blurb:"Social democrat, Ostpolitik détente policy.", aliases:["willy brandt","brandt"]},

  // --- rest of world (current-ish) ---
  {name:"Volodymyr Zelenskyy", country:"Ukraine", dates:"2019–present", x:-1, y:2, blurb:"Wartime democratic leader, some emergency-powers debate.", aliases:["zelensky","zelenskyy","volodymyr zelensky"]},
  {name:"Narendra Modi", country:"India", dates:"2014–present", x:3, y:-3, blurb:"Hindu-nationalist right, market reforms, press-freedom concerns.", aliases:["modi","narendra modi"]},
  {name:"Justin Trudeau", country:"Canada", dates:"2015–2025", x:-2, y:4, blurb:"Center-left Liberal, standard democratic governance.", aliases:["trudeau","justin trudeau"]},
  {name:"Giorgia Meloni", country:"Italy", dates:"2022–present", x:4, y:-1, blurb:"National-conservative right, within EU democratic norms.", aliases:["meloni","giorgia meloni"]},
  {name:"Pedro Sánchez", country:"Spain", dates:"2018–present", x:-3, y:3, blurb:"Center-left PSOE, standard democratic governance.", aliases:["pedro sanchez","sanchez"]},
  {name:"Lula da Silva", country:"Brazil", dates:"2003–2011, 2023–present", x:-5, y:3, blurb:"Left-leaning Workers' Party, democratic governance.", aliases:["lula","lula da silva"]},
  {name:"Jair Bolsonaro", country:"Brazil", dates:"2019–2023", x:5, y:-4, blurb:"Right-populist, some institutional-norm controversies.", aliases:["bolsonaro","jair bolsonaro"]},
  {name:"Javier Milei", country:"Argentina", dates:"2023–present", x:9, y:0, blurb:"Libertarian free-market radical, minimal-state agenda.", aliases:["milei","javier milei"]},
  {name:"Cyril Ramaphosa", country:"South Africa", dates:"2018–present", x:-3, y:3, blurb:"Center-left ANC, democratic governance.", aliases:["ramaphosa","cyril ramaphosa"]},
  {name:"Anthony Albanese", country:"Australia", dates:"2022–present", x:-3, y:4, blurb:"Center-left Labor, standard democratic governance.", aliases:["albanese","anthony albanese"]},
  {name:"Benjamin Netanyahu", country:"Israel", dates:"1996–1999, 2009–present", x:6, y:-3, blurb:"Right-leaning market reforms, judicial-overhaul controversy.", aliases:["netanyahu","bibi","benjamin netanyahu"]}
];
